# SPDX-FileCopyrightText: 2024 Toki Makabe <s23c1130sm@s.chibakoudai.jp>
# SPDX-License-Identifier:BSD-3-Clause

name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest 
    steps:
      - uses: actions/checkout@v2    
      - name: build and test
        run: |

          ros2 pkg create mypkg
          cd root/ros2_ws
          colcon build
          source install/setup.bash

          ros2 pkg list | grep mypkg

          rsync -av ./ /root/ros2_ws/src/mypkg/    
          cd /root/ros2_ws
          bash -xv ./src/mypkg/test/test.bash /root

          
