name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest 
    steps:
      - uses: actions/checkout@v2    
      - name: build and test
        run: |
          geckodriver &
          Xvfb -ac :99 -screen 0 1280x1024x24
          export DISPLAY=:99
          rsync -av ./ /root/ros2_ws/src/mypkg/    
          cd /root/ros2_ws
          bash -xv ./src/mypkg/test/test.bash /root

          
